fix PHP error on CollaborationListContent pages
Error: Call to undefined method
MediaWiki\Output\OutputPage::preventClickjacking()

After this patch, a page with content model
CollaborationListContent will go from throwing a PHP
error, to displaying JSON. Displaying JSON is also a
bug (T366815), but this patch is an incremental improvement.

This extension is not WMF-deployed and has been unusable
since MW 1.42 due to serious bugs. I am trying to get it
usable again.

Change-Id: Ib4fb99dcb611976aac77e4c694b21605e1b2111e